package PacketSender;

import java.io.Serializable;


/**
 * Uses for hands all the commands that will use for client requests and server handling
 *
 */
public enum Command implements Serializable
{
	getUsers,
	getUserByuId,
	getUserByIdAndPass,
	setUserLoggedInState,
	getStudentByuId,
	getlecturerByUid,
	getCoursesbyLid,
	getCoursesbySid,
	getExamsbyCid,
	getGradesbySid,
	addQuestion,
	getQuestion,
	getExamBySid,
	getAVGBySid,
	getDepartmentByLid,
	getExams,
	UpdateCodeExam,
	getExamByExCode,
	getCountExamByCid,
	addExam,
	getQuestionByCid,
	getExamByExamId,
	getQuestionsByExamId,
	getDepartmentIDByUid,
	getAllLecturers,
	getAllCourses,
	getAllStudents,
	getQuestionsByExID,
	AddcheckedQuestions,
	getCourseIDbyExamID,
	getExamByExamIdAndSid,
	addQuestionInExam,
	getALLlecturersRequests,
	getLecturerReason,
	getOnlineExamByLecturer,
	getDepartmentIDByUidLecturer,
	getExamCopyByCidAndSid, 
	getExamsBySidAndCid,
	addDeclineAnswerFromPrincipal,
	addApproveAnswerFromPrincipal,
	SetActiveExam,
	updateIsLocked,
	updateExtraTime,
	AddFinishedExam,
	getExamTime,
	getStudentAvg,
	getStudentMedian,
	getAvgbyCourseName,
	getMedianbyCourseName,
	getAvgOfLecturer,
	getMedianOfLecturer,
	CheckCodeExam,
	getAnsweredQuestionSidAndQid,
	getExtraTime,
	getExamBySidCheckExam,
	getQuestionsByExIDCheckExam,
	updateQuestionNote,
	getStudentByCid,
	getExamByLecturerID,
	addExamToChangeTime,
	getDataStudentBySid,
	getGradeCourseName,
	updateStudentGrade,
	updateStudentAvg,
	getLecturerUidAndCourseNamebyExamID,
	updateStudentGradeInExam,
	getFinishedExamFlagByExId,
	updateChangeGradeReason,
	checkLockedExam,
	uploadFile,
	addDoneExamDetails,
	getExamByExamIdAndSidManual,
	AddFinishedExamManual,
	updateDateExam,
	updateTotalTime,
	updateExamStatistics,
	saveCurrentGrade,
	getLockedExamCourses,
	getExamByCourseID,
	getFinishedQuestionsByExID,
	updateAccess,
	checkStatistics,
	UpdateCountReportCourse,
	getGradeCourseByCId,
	UpdateLecturercReport,
	getGradeLecturerBylId,
	initExam,
	getAllQuestions,
	addExamIdToReportExamTime,
	getAvgForExamByExId,
	getMedForExamByExId,
	updateAvgForExamIdByExId,
	updateMedForExamIdByExId,
	getStudentInstructions,
	getLecturerInstructions,
	
	
	
	
}
